### ISSUE TITLE
Pydantic 2 support - is_classvar

### ISSUE THREAD

**Issue by ashupednekar** [fastapiutils/fastapi-utils#283]
**Is your feature request related to a problem? Please describe.**
I'm only trying to use the class based views from this library. In order to support pydantic 2

**Describe the solution you'd like**
I understand that there are other open PR's addressing pydantic 2 support. 
Since I'm only trying to use cbv decorator for class based view, I would like the is_classvar issue to be fixed first, so that it can be used in conjunction with pydantic 2, while the rest of the fixes are being developed.

**Describe alternatives you've considered**
If this PR is not merged, I would continue to use a fork internally, till #276 is merged

**Additional context**
We're migrating from Django rest to fastapi...  so class based views are a must for us. I'm building out essential functionalities from DRF, so that we can retain the structured and maintainable code base we already have

**Comment by yuval9313** [comment]
It is supposed to be fixed in version 0.6.0 following #291, Update if more help is needed
