### ISSUE TITLE
[QUESTION] Package/version confusion

### ISSUE THREAD

**Issue by kevinhikaruevans** [fastapiutils/fastapi-utils#317]
**Description**

Hi, I'm a little confused on the package and versions. On the website https://fastapi-utils.davidmontague.xyz/, it says to install `fastapi-restful`, which is a different package. The Github README says to install `fastapi-utils`. 

And on https://fastapi-utils.davidmontague.xyz/user-guide/class-resource/, the imports are for `fastapi_utils`. 

Which package has the latest code? Which one should I be using? I see this issue https://github.com/dmontagu/fastapi-utils/issues/292 but I'm still confused to what package is correct. Thanks!

**Comment by yuval9313** [comment]
It is resolve and caused due to error in the docs page, sorry
