### ISSUE TITLE
[BUG] Install Documentation out of Date 

### ISSUE THREAD

**Issue by S010MON** [fastapiutils/fastapi-utils#325]
**Description**
Not quite a bug, but more of a note for your documentation, you seem to have updated the PyPi install instructions, but it doesn't seem to have built the ones at https://fastapi-utils.davidmontague.xyz/ to use `fastapi-utils` 

Great project, really solved a problem for me in a simple way, thanks very much!

**Screenshots**
### https://fastapi-utils.davidmontague.xyz/
![image](https://github.com/dmontagu/fastapi-utils/assets/10490509/cf788efe-534d-400c-8518-8d3ee10e3097)

### https://pypi.org/project/fastapi-utils/
![image](https://github.com/dmontagu/fastapi-utils/assets/10490509/6de08fcb-3a85-496b-ac1b-998ab1cfb507)

**Comment by yuval9313** [comment]
Fixed
