### ISSUE TITLE
How use exclude In fastapi-utils?

### ISSUE THREAD

**Issue by ciaoyizhen** [fastapiutils/fastapi-utils#330]
In fastapi Document:
```
@app.get("/items/{item_id}/public", response_model=Item, response_model_exclude={"tax"})
async def read_item_public_data(item_id: str):
    return items[item_id]
```
We can use response_model_exclude

In fastapi-utils:
```
class MyApi(Resource):
    def __init__(self, mongo_client):
        self.mongo = mongo_client

    @set_responses(ResponseModel)
    def get(self):
        return "Done"
  ```
how to set exclude

**Comment by ciaoyizhen** [comment]
@dmontagu 
Hi, I was wondering if this repository is still up to date. It seems like it hasn't been for a long time.
And the issue isn't very active.

**Comment by yuval9313** [comment]
It should work simply by using `@set_responses(ResponseModel, response_model_exclude={"tax"})`
